<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\TestProject.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ECommerceBackend\ECommerceBackend.csproj" />
  </ItemGroup>

</Project>
